version: "3.9"

name: saloncedevcomapp

services:
  mysqldb:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: 'mysql@sha256:a13510e6c70e4be896cb904ba1fe3d4d466193928324744bb2356e865c097ebb'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_USER: ${MYSQL_DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    volumes:
      - saloncedevcomdata:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 5s
          retries: 30
    networks:
      - appsnetwork

  backend:
    container_name: saloncedevcom-backend
    environment:
      MYSQL_HOSTNAME: ${MYSQL_CONTAINER_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
    build:
      context: ./backend-todolist/
      dockerfile: dockerfile
    image: saloncedevcombackend:0
    depends_on:
      mysqldb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/todo/task"]
      timeout: 5s
      retries: 30
    ports:
      - '8080:8080'
    networks:
      - appsnetwork

  frontend:
    container_name: saloncedevcom-frontend
    build:
      context: ./frontend-react/
      dockerfile: dockerfile
    image: saloncedevcomfrontend:0
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '${ACCESS_PORT}:80'
    networks:
      - appsnetwork



networks:
  appsnetwork:

volumes:
  saloncedevcomdata: